import { getPublishedProducts, getProductBySlug as dbGetProductBySlug } from './local-db'

export type Product = {
  id: string
  name: string
  slug: string
  price: number
  salePrice?: number
  image: string
  category: string
  collection: string
  colors: string[]
  sizes: string[]
  badge?: string
  inStock: boolean
}

type DbProduct = Awaited<ReturnType<typeof getPublishedProducts>>[number]

/**
 * Map a database Product to the site Product type.
 */
function mapToSiteProduct(p: DbProduct): Product {
  const badgeMap: Record<string, string> = {
    new: 'New',
    sale: 'Sale',
    trending: 'Trending',
    limited: 'Limited',
  }

  const firstTag = p.tags?.[0]?.toLowerCase() || ''
  const badge = badgeMap[firstTag] || (p.tags?.includes('new') ? 'New' : undefined)

  return {
    id: p.id,
    name: p.name,
    slug: p.slug,
    price: p.price,
    salePrice: p.salePrice ?? undefined,
    image: p.thumbnail || p.images?.[0] || '/placeholder.svg',
    category: p.category || '',
    collection: typeof p.collection === 'string' ? p.collection : '',
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge,
    inStock: p.stockQuantity > 0,
  }
}

/**
 * Get all published products for the storefront.
 * Returns a Promise since it may fetch from Supabase.
 */
export async function getSiteProducts(): Promise<Product[]> {
  try {
    const dbProducts = await getPublishedProducts()
    return dbProducts.map(mapToSiteProduct)
  } catch {
    return []
  }
}

/**
 * Get a single product by slug for the product detail page.
 */
export async function getSiteProductBySlug(slug: string): Promise<Product | undefined> {
  try {
    const dbProduct = await dbGetProductBySlug(slug)
    if (!dbProduct || dbProduct.status !== 'published') return undefined
    return mapToSiteProduct(dbProduct)
  } catch {
    return undefined
  }
}

// Static fallback for SSR / build time (server component usage)
// Client components should call getSiteProducts() instead
export const products: Product[] = [
  {
    id: 'p1',
    name: "Make SA Great Again Tee",
    slug: "make-sa-great-again-tee",
    price: 350,
    image: "/products/make-sa-great-again-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'New',
    inStock: true,
  },
  {
    id: 'p2',
    name: "Girls First Tee",
    slug: "girls-first-tee",
    price: 350,
    image: "/products/girls-first-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'New',
    inStock: true,
  },
  {
    id: 'p3',
    name: "Renaissance Landscape Tee",
    slug: "renaissance-landscape-tee",
    price: 350,
    image: "/products/renaissance-landscape-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'New',
    inStock: true,
  },
  {
    id: 'p4',
    name: "No Hoes Allowed Tee",
    slug: "no-hoes-allowed-tee",
    price: 350,
    image: "/products/no-hoes-allowed-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'New',
    inStock: true,
  },
  {
    id: 'p5',
    name: "Renaissance L.N.D Winter Tee",
    slug: "renaissance-lnd-winter-tee",
    price: 350,
    image: "/products/renaissance-lnd-winter-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'New',
    inStock: true,
  },
  {
    id: 'p6',
    name: "You've Just Seen A... Tee",
    slug: "pornstar-tee",
    price: 350,
    image: "/products/pornstar-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'New',
    inStock: true,
  },
  {
    id: 'p7',
    name: "I Love A$$ Tee",
    slug: "i-love-ass-tee",
    price: 350,
    image: "/products/i-love-ass-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'New',
    inStock: true,
  },
  {
    id: 'p8',
    name: "HOR NY Tee",
    slug: "horny-ny-tee",
    price: 350,
    image: "/products/horny-ny-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'New',
    inStock: true,
  },
  {
    id: 'p9',
    name: "Jack Portrait Tee",
    slug: "jack-portrait-tee",
    price: 380,
    image: "/products/jack-portrait-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p10',
    name: "Renaissance 00 Jersey",
    slug: "renaissance-00-jersey",
    price: 380,
    image: "/products/renaissance-00-jersey.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p11',
    name: "So Sick Of This Shit Tee",
    slug: "so-sick-tee",
    price: 350,
    image: "/products/so-sick-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p12',
    name: "Love Tag Tee",
    slug: "love-tag-tee",
    price: 350,
    image: "/products/love-tag-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p13',
    name: "I Want To Get High Tee",
    slug: "high-sex-tee",
    price: 350,
    image: "/products/high-sex-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p14',
    name: "Renaissance L.N.D Crop",
    slug: "renaissance-lnd-crop",
    price: 320,
    image: "/products/renaissance-lnd-crop.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p15',
    name: "I Heart Renaissance Tee",
    slug: "i-heart-renaissance-tee",
    price: 350,
    image: "/products/i-heart-renaissance-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p16',
    name: "Faces Grid Tee",
    slug: "faces-grid-tee",
    price: 380,
    image: "/products/faces-grid-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p17',
    name: "Infant Boys Club Tee",
    slug: "infant-boys-club-tee",
    price: 350,
    image: "/products/infant-boys-club-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p18',
    name: "Pan-African Logo Tee",
    slug: "pan-african-logo-tee",
    price: 350,
    image: "/products/pan-african-logo-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p19',
    name: "Renaissance Logo Crewneck",
    slug: "renaissance-logo-crewneck",
    price: 550,
    image: "/products/renaissance-logo-crewneck.png",
    category: "Outerwear",
    collection: "Heavyweight",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p20',
    name: "Renaissance Logo Hoodie",
    slug: "renaissance-logo-hoodie",
    price: 650,
    image: "/products/renaissance-logo-hoodie.png",
    category: "Outerwear",
    collection: "Heavyweight",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p21',
    name: "Stars & Flame Hoodie",
    slug: "renaissance-stars-flame-hoodie",
    price: 720,
    image: "/products/renaissance-stars-flame-hoodie.png",
    category: "Outerwear",
    collection: "Heavyweight",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p22',
    name: "Renaissance Eagles Hoodie",
    slug: "renaissance-eagles-hoodie",
    price: 720,
    image: "/products/renaissance-eagles-hoodie.png",
    category: "Outerwear",
    collection: "Heavyweight",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p23',
    name: "Billion Dollar Gang Crewneck",
    slug: "billion-dollar-gang-crewneck",
    price: 600,
    image: "/products/billion-dollar-gang-crewneck.png",
    category: "Outerwear",
    collection: "Billion Dollar Gang",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p24',
    name: "Crimson Angels Sleeve Script",
    slug: "crimson-sleeve-script-crew",
    price: 580,
    image: "/products/crimson-sleeve-script-crew.png",
    category: "Outerwear",
    collection: "Crimson Angels",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p25',
    name: "Crimson Angels Polo",
    slug: "crimson-polo",
    price: 450,
    image: "/products/crimson-polo.png",
    category: "Tops",
    collection: "Crimson Angels",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p26',
    name: "Crimson Angels Monroe Crew",
    slug: "crimson-monroe-crew",
    price: 620,
    image: "/products/crimson-monroe-crew.png",
    category: "Outerwear",
    collection: "Crimson Angels",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p27',
    name: "Crimson Angels Script Hoodie",
    slug: "crimson-script-hoodie",
    price: 680,
    image: "/products/crimson-script-hoodie.png",
    category: "Outerwear",
    collection: "Crimson Angels",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p28',
    name: "Crimson Angels Side Tank",
    slug: "crimson-side-tank",
    price: 320,
    image: "/products/crimson-side-tank.png",
    category: "Tops",
    collection: "Crimson Angels",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p29',
    name: "Crimson Angels Lagos Crest",
    slug: "crimson-lagos-crest-crew",
    price: 600,
    image: "/products/crimson-lagos-crest-crew.png",
    category: "Outerwear",
    collection: "Crimson Angels",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p30',
    name: "BDG Astronaut Tee (Black)",
    slug: "bdg-astronaut-black-tee",
    price: 350,
    image: "/products/bdg-astronaut-black-tee.png",
    category: "Tops",
    collection: "Billion Dollar Gang",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p31',
    name: "BDG Public Enemy Tee",
    slug: "bdg-public-enemy-tee",
    price: 380,
    image: "/products/bdg-public-enemy-tee.png",
    category: "Tops",
    collection: "Billion Dollar Gang",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p32',
    name: "BDG Block Logo Tee",
    slug: "bdg-block-logo-tee",
    price: 350,
    image: "/products/bdg-block-logo-tee.png",
    category: "Tops",
    collection: "Billion Dollar Gang",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p33',
    name: "BDG Astronaut Tee (White)",
    slug: "bdg-astronaut-white-tee",
    price: 350,
    image: "/products/bdg-astronaut-white-tee.png",
    category: "Tops",
    collection: "Billion Dollar Gang",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p34',
    name: "BDG Chrome Figure Tee",
    slug: "bdg-chrome-figure-tee",
    price: 400,
    image: "/products/bdg-chrome-figure-tee.png",
    category: "Tops",
    collection: "Billion Dollar Gang",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p35',
    name: "BDG Diamond Figure Tee",
    slug: "bdg-diamond-figure-tee",
    price: 400,
    image: "/products/bdg-diamond-figure-tee.png",
    category: "Tops",
    collection: "Billion Dollar Gang",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p36',
    name: "BDG Crayon Tee",
    slug: "bdg-crayon-tee",
    price: 400,
    image: "/products/bdg-crayon-tee.png",
    category: "Tops",
    collection: "Billion Dollar Gang",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p37',
    name: "We Are Fucking Angry Tee",
    slug: "we-are-fucking-angry-tee",
    price: 350,
    image: "/products/we-are-fucking-angry-tee.png",
    category: "Tops",
    collection: "Renaissance Tees",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p38',
    name: "BDG Pixel Green Tee",
    slug: "bdg-pixel-green-tee",
    price: 350,
    image: "/products/bdg-pixel-green-tee.png",
    category: "Tops",
    collection: "Billion Dollar Gang",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p39',
    name: "No Hoes Allowed Baby Tee",
    slug: "no-hoes-baby-tee",
    price: 320,
    image: "/products/no-hoes-baby-tee.png",
    category: "Tops",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p40',
    name: "Money Makes Me Tank",
    slug: "money-makes-me-tank",
    price: 280,
    image: "/products/money-makes-me-tank.png",
    category: "Tops",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p41',
    name: "Girls First Baby Tee",
    slug: "girls-first-baby-tee",
    price: 320,
    image: "/products/girls-first-baby-tee.png",
    category: "Tops",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p42',
    name: "Love Tag Baby Tee",
    slug: "love-tag-baby-tee",
    price: 320,
    image: "/products/love-tag-baby-tee.png",
    category: "Tops",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p43',
    name: "HOR NY Baby Tee",
    slug: "horny-ny-baby-tee",
    price: 320,
    image: "/products/horny-ny-baby-tee.png",
    category: "Tops",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p44',
    name: "NAKED Distressed Tank",
    slug: "naked-distressed-tank",
    price: 300,
    image: "/products/naked-distressed-tank.png",
    category: "Tops",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p45',
    name: "NAKED Denim Mini",
    slug: "naked-denim-mini",
    price: 420,
    image: "/products/naked-denim-mini.png",
    category: "Bottoms",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p46',
    name: "SEX. Distressed Tank",
    slug: "sex-distressed-tank",
    price: 300,
    image: "/products/sex-distressed-tank.png",
    category: "Tops",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p47',
    name: "EBONY Baby Tee",
    slug: "ebony-baby-tee",
    price: 300,
    image: "/products/ebony-baby-tee.png",
    category: "Tops",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p48',
    name: "Halo Girl Tank",
    slug: "halo-girl-tank",
    price: 320,
    image: "/products/halo-girl-tank.png",
    category: "Tops",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p49',
    name: "EBONY Denim Mini",
    slug: "ebony-denim-mini",
    price: 420,
    image: "/products/ebony-denim-mini.png",
    category: "Bottoms",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p50',
    name: "MOWA Shorts",
    slug: "mowa-shorts",
    price: 280,
    image: "/products/mowa-shorts.png",
    category: "Bottoms",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p51',
    name: "Camo Stars Shorts",
    slug: "camo-stars-shorts",
    price: 450,
    image: "/products/camo-stars-shorts.png",
    category: "Bottoms",
    collection: "Bottoms Archive",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p52',
    name: "Renaissance Logo Shorts",
    slug: "logo-denim-shorts",
    price: 420,
    image: "/products/logo-denim-shorts.png",
    category: "Bottoms",
    collection: "Bottoms Archive",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p53',
    name: "Flame Side Shorts",
    slug: "flame-side-shorts",
    price: 450,
    image: "/products/flame-side-shorts.png",
    category: "Bottoms",
    collection: "Bottoms Archive",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p54',
    name: "Vertical Logo Sweats",
    slug: "vertical-logo-sweats",
    price: 520,
    image: "/products/vertical-logo-sweats.png",
    category: "Bottoms",
    collection: "Bottoms Archive",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p55',
    name: "HOR NY Sweats",
    slug: "horny-ny-sweats",
    price: 520,
    image: "/products/horny-ny-sweats.png",
    category: "Bottoms",
    collection: "Bottoms Archive",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p56',
    name: "Logo Seat Joggers",
    slug: "logo-seat-joggers",
    price: 500,
    image: "/products/logo-seat-joggers.png",
    category: "Bottoms",
    collection: "Bottoms Archive",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p57',
    name: "Crimson Angels Beanie",
    slug: "crimson-angels-beanie",
    price: 220,
    image: "/products/crimson-angels-beanie.png",
    category: "Accessories",
    collection: "Crimson Angels",
    colors: ['Default'],
    sizes: ['OS'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p58',
    name: "Camo Graffiti Cap",
    slug: "camo-graffiti-cap",
    price: 280,
    image: "/products/camo-graffiti-cap.png",
    category: "Accessories",
    collection: "Accessories",
    colors: ['Default'],
    sizes: ['OS'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p59',
    name: "EBONY Block Tee",
    slug: "ebony-block-tee",
    price: 300,
    image: "/products/ebony-block-tee.png",
    category: "Tops",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p60',
    name: "Crimson Angels Heart Tee",
    slug: "crimson-heart-tee",
    price: 350,
    image: "/products/crimson-heart-tee.png",
    category: "Tops",
    collection: "Crimson Angels",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
  {
    id: 'p61',
    name: "EBONY NY Tee",
    slug: "ebony-ny-tee",
    price: 320,
    image: "/products/ebony-ny-tee.png",
    category: "Tops",
    collection: "Girls Drop",
    colors: ['Default'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: undefined,
    inStock: true,
  },
]

export const reviews = [
  {
    name: 'Aria Vance',
    handle: '@ariavance',
    quote:
      'It does not feel like clothing. It feels like wearing the future. The chrome puffer is unreal in person.',
  },
  {
    name: 'Kenji Mori',
    handle: '@kenji.mori',
    quote:
      'Renaissance is the only brand making Y2K feel genuinely luxurious instead of costume. Obsessed.',
  },
  {
    name: 'Sloane Reyes',
    handle: '@sloanereyes',
    quote:
      'Every drop sells out for a reason. The detailing and quality are on another level entirely.',
  },
]
